[project]
name = 'Decentralized-Voting-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ballot]
path = 'contracts/ballot.clar'
clarity_version = 2
epoch = 2.5

[contracts.result-verification]
path = 'contracts/result-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.vote-counting]
path = 'contracts/vote-counting.clar'
clarity_version = 2
epoch = 2.5

[contracts.voter-registration]
path = 'contracts/voter-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
